# REST + H2 (in-memory, resets each restart)
# Loaded only when profile=h2

spring:
  config:
    activate:
      on-profile: h2           # bind this file to profile=h2
  datasource:
    url: jdbc:h2:mem:bank_dev;MODE=MySQL;DB_CLOSE_DELAY=0
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop    # build schema on start, drop on shutdown
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8081
