# MVC calls the REST API
server:
  port: 8082                 # MVC port

spring:
  thymeleaf:
    cache: false             # hot reload templates

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG  # log outgoing REST calls

bank:
  api:
    base-url: http://localhost:8081   # REST sits here (both H2/MySQL profiles)
    customers-path: /api/customers
    auth:
      type: basic
      username: api
      password: secret
