spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank?useSSL=false&serverTimezone=UTC
    username: root
    password: kuwe123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
